services:
    db:
        image: postgres:13
        restart: always
        container_name: blog-db
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: blog
            POSTGRES_PASSWORD: blogpass667
            POSTGRES_DB: blog
        volumes:
            - .docker/dbdata:/var/lib/postgres

    blog:
        build: .
        container_name: blog
        restart: always
        ports:
            - 3001:3001
        volumes:
            - .:/usr/src/app
        links:
            - db
        depends_on:
            - db

volumes:
    pgdata:
        driver: local
