// Create User
POST http://localhost:3001/users/
content-type: application/json

{
    "email": "bob@mail.com",
    "password": "pass123"
}

###
// get all users
GET http://localhost:3001/users/

###
// Authenticate User
POST http://localhost:3001/users/login
content-type: application/json

{
    "email": "bob@mail.com2",
    "password": "pass123"
}
